sections:
- module: "Zawory"
  buttons:
    - name: "Zawór 1"
      code: 0x01
    - name: "Zawór 2"
      code: 0x02
    - name: "Zawór 3"
      code: 0x03
    - name: "Zawór 4"
      code: 0x04
    - name: "Zawór 5"
      code: 0x05
    - name: "Zawór 6"
      code: 0x06
    - name: "Zawór 7"
      code: 0x07
    - name: "Zawór 8"
      code: 0x08

- module: "Piezopompy"
  buttons:
    - name: "Piezopompa 1"
      code: 0x11
    - name: "Piezopompa 2"
      code: 0x12
    - name: "Piezopompa 3"
      code: 0x13
    - name: "Piezopompa 4"
      code: 0x14

- module: "Pompy perystaltyczne"
  buttons:
    - name: "Pompa 1"
      code: 0x21
    - name: "Pompa 2"
      code: 0x22
    - name: "Pompa 3"
      code: 0x23
    - name: "Pompa 4"
      code: 0x24
    - name: "Pompa 5"
      code: 0x25
    - name: "Pompa 6"
      code: 0x26
    - name: "Pompa 7"
      code: 0x27
    - name: "Pompa 8"
      code: 0x28