name: Continuous Integration (CI)

on:
  push:
    branches: [ "develop_gui" ]

jobs:
  check-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies (udev)
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev pkg-config

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Rust Cache
      uses: swatinem/rust-cache@v2

    - name: Run Cargo Build (Debug)
      working-directory: gravite_hydrotest
      run: cargo build